# -*- coding: utf-8 -*-
"""worldcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2cr2zD0ScVbuP38zqE7dS1kF6j7rWfM
"""

# exercice 1
# author : BAZILLON
# state : ongoing

# exercice 2
# author : LA
# state : ongoing

# exercice 3
# author : ADBC
# state : ongoing

# exercice 4
# author : OA
# state : ongoing